name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  mobile_scanner: ^6.0.7
  url_launcher: ^6.3.1
  get: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
